replicaCount: 3

image:
  name: localhost:5000/web-api
  pullPolicy: Always
  tag: "1.0"

containers:
  name: web-api

imagePullSecrets: []
nameOverride: "api"
fullnameOverride: "api"
label: web-api

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 8080
  expose: 3000

ingress:
  enabled: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
