apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  selector:
    app: {{ .Values.label }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.expose }}
      targetPort: {{ .Values.service.port }}